//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.13.1
//     from Assets/Scripts/interactions/ManipulationInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/interactions/ManipulationInput.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @ManipulationInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @ManipulationInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ManipulationInput"",
    ""maps"": [
        {
            ""name"": ""Manipulation"",
            ""id"": ""1bfd215d-ae0c-468c-b618-7bbade6639cd"",
            ""actions"": [
                {
                    ""name"": ""ModeWhole"",
                    ""type"": ""Button"",
                    ""id"": ""8bb204aa-dc9a-45d3-8622-11e5732b162e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ModeSuperior"",
                    ""type"": ""Button"",
                    ""id"": ""deb18107-04b9-4ea8-ac6f-a5f882e9f58c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ModeInferior"",
                    ""type"": ""Button"",
                    ""id"": ""cce91b7a-0481-4dd3-99b1-f30ce27e4760"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""d503252e-dc41-4dc6-93c6-077725956180"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveY"",
                    ""type"": ""Value"",
                    ""id"": ""2139dca8-21a2-4863-9aeb-42e166262f6b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""eabb8b96-1bb8-4f0b-8591-778151ebafbb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CycleMode"",
                    ""type"": ""Button"",
                    ""id"": ""179ee8a4-37d5-4465-b5ae-bf1a5972f8e5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveUp"",
                    ""type"": ""Button"",
                    ""id"": ""9b93836e-14b0-4b86-a1fa-9f8a30202823"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveDown"",
                    ""type"": ""Button"",
                    ""id"": ""473ead3d-482e-40c7-9f5a-43b661a39d99"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ResetTransform"",
                    ""type"": ""Button"",
                    ""id"": ""6931b1a4-5180-4ab5-9993-373dbae104bc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""646fa322-e13f-4bad-a9d7-a6af84bacdb7"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ModeWhole"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a33d8d2-9ded-4523-8137-3f2738a8b549"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ModeSuperior"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f260b5be-03e5-44c0-9501-c6fb818302e9"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ModeInferior"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""ab8076f5-540c-4969-978c-9e2d81b98578"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6a47aa73-0595-420e-9eef-77ab00db8bed"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""941e549c-94ed-499f-b3ad-c61066cbdad4"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""72aca475-bc75-44e8-a69d-20729817d2a0"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8ad6061e-8ec6-4414-9917-8c90633b526c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f69c1b2c-7ef2-4c06-9736-aec776872a1a"",
                    ""path"": ""<XRController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""d3501d6d-e12c-4fbf-b1fe-0da26ad0c732"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveY"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""84861082-c533-401c-9b68-16aaca2e933f"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""fd1a2653-cedf-4951-b499-dafbbe88da0d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""24520421-b02e-4599-b855-e46adee1d52d"",
                    ""path"": ""<XRController>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60892806-b112-4137-9c14-25288f23ab3a"",
                    ""path"": ""<XRController>{RightHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CycleMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59e1dc52-c983-429a-a7e8-750d9edc8bd8"",
                    ""path"": ""<XRController>{LeftHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67c51790-d829-4354-96fc-5d6f9f1a40ca"",
                    ""path"": ""<XRController>{LeftHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a5235a4-f11b-4f31-b1ef-a058cc43d3b8"",
                    ""path"": ""<XRController>{RightHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetTransform"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Manipulation
        m_Manipulation = asset.FindActionMap("Manipulation", throwIfNotFound: true);
        m_Manipulation_ModeWhole = m_Manipulation.FindAction("ModeWhole", throwIfNotFound: true);
        m_Manipulation_ModeSuperior = m_Manipulation.FindAction("ModeSuperior", throwIfNotFound: true);
        m_Manipulation_ModeInferior = m_Manipulation.FindAction("ModeInferior", throwIfNotFound: true);
        m_Manipulation_Move = m_Manipulation.FindAction("Move", throwIfNotFound: true);
        m_Manipulation_MoveY = m_Manipulation.FindAction("MoveY", throwIfNotFound: true);
        m_Manipulation_Rotate = m_Manipulation.FindAction("Rotate", throwIfNotFound: true);
        m_Manipulation_CycleMode = m_Manipulation.FindAction("CycleMode", throwIfNotFound: true);
        m_Manipulation_MoveUp = m_Manipulation.FindAction("MoveUp", throwIfNotFound: true);
        m_Manipulation_MoveDown = m_Manipulation.FindAction("MoveDown", throwIfNotFound: true);
        m_Manipulation_ResetTransform = m_Manipulation.FindAction("ResetTransform", throwIfNotFound: true);
    }

    ~@ManipulationInputActions()
    {
        UnityEngine.Debug.Assert(!m_Manipulation.enabled, "This will cause a leak and performance issues, ManipulationInputActions.Manipulation.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Manipulation
    private readonly InputActionMap m_Manipulation;
    private List<IManipulationActions> m_ManipulationActionsCallbackInterfaces = new List<IManipulationActions>();
    private readonly InputAction m_Manipulation_ModeWhole;
    private readonly InputAction m_Manipulation_ModeSuperior;
    private readonly InputAction m_Manipulation_ModeInferior;
    private readonly InputAction m_Manipulation_Move;
    private readonly InputAction m_Manipulation_MoveY;
    private readonly InputAction m_Manipulation_Rotate;
    private readonly InputAction m_Manipulation_CycleMode;
    private readonly InputAction m_Manipulation_MoveUp;
    private readonly InputAction m_Manipulation_MoveDown;
    private readonly InputAction m_Manipulation_ResetTransform;
    /// <summary>
    /// Provides access to input actions defined in input action map "Manipulation".
    /// </summary>
    public struct ManipulationActions
    {
        private @ManipulationInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ManipulationActions(@ManipulationInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Manipulation/ModeWhole".
        /// </summary>
        public InputAction @ModeWhole => m_Wrapper.m_Manipulation_ModeWhole;
        /// <summary>
        /// Provides access to the underlying input action "Manipulation/ModeSuperior".
        /// </summary>
        public InputAction @ModeSuperior => m_Wrapper.m_Manipulation_ModeSuperior;
        /// <summary>
        /// Provides access to the underlying input action "Manipulation/ModeInferior".
        /// </summary>
        public InputAction @ModeInferior => m_Wrapper.m_Manipulation_ModeInferior;
        /// <summary>
        /// Provides access to the underlying input action "Manipulation/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_Manipulation_Move;
        /// <summary>
        /// Provides access to the underlying input action "Manipulation/MoveY".
        /// </summary>
        public InputAction @MoveY => m_Wrapper.m_Manipulation_MoveY;
        /// <summary>
        /// Provides access to the underlying input action "Manipulation/Rotate".
        /// </summary>
        public InputAction @Rotate => m_Wrapper.m_Manipulation_Rotate;
        /// <summary>
        /// Provides access to the underlying input action "Manipulation/CycleMode".
        /// </summary>
        public InputAction @CycleMode => m_Wrapper.m_Manipulation_CycleMode;
        /// <summary>
        /// Provides access to the underlying input action "Manipulation/MoveUp".
        /// </summary>
        public InputAction @MoveUp => m_Wrapper.m_Manipulation_MoveUp;
        /// <summary>
        /// Provides access to the underlying input action "Manipulation/MoveDown".
        /// </summary>
        public InputAction @MoveDown => m_Wrapper.m_Manipulation_MoveDown;
        /// <summary>
        /// Provides access to the underlying input action "Manipulation/ResetTransform".
        /// </summary>
        public InputAction @ResetTransform => m_Wrapper.m_Manipulation_ResetTransform;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Manipulation; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ManipulationActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ManipulationActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ManipulationActions" />
        public void AddCallbacks(IManipulationActions instance)
        {
            if (instance == null || m_Wrapper.m_ManipulationActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ManipulationActionsCallbackInterfaces.Add(instance);
            @ModeWhole.started += instance.OnModeWhole;
            @ModeWhole.performed += instance.OnModeWhole;
            @ModeWhole.canceled += instance.OnModeWhole;
            @ModeSuperior.started += instance.OnModeSuperior;
            @ModeSuperior.performed += instance.OnModeSuperior;
            @ModeSuperior.canceled += instance.OnModeSuperior;
            @ModeInferior.started += instance.OnModeInferior;
            @ModeInferior.performed += instance.OnModeInferior;
            @ModeInferior.canceled += instance.OnModeInferior;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @MoveY.started += instance.OnMoveY;
            @MoveY.performed += instance.OnMoveY;
            @MoveY.canceled += instance.OnMoveY;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
            @CycleMode.started += instance.OnCycleMode;
            @CycleMode.performed += instance.OnCycleMode;
            @CycleMode.canceled += instance.OnCycleMode;
            @MoveUp.started += instance.OnMoveUp;
            @MoveUp.performed += instance.OnMoveUp;
            @MoveUp.canceled += instance.OnMoveUp;
            @MoveDown.started += instance.OnMoveDown;
            @MoveDown.performed += instance.OnMoveDown;
            @MoveDown.canceled += instance.OnMoveDown;
            @ResetTransform.started += instance.OnResetTransform;
            @ResetTransform.performed += instance.OnResetTransform;
            @ResetTransform.canceled += instance.OnResetTransform;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ManipulationActions" />
        private void UnregisterCallbacks(IManipulationActions instance)
        {
            @ModeWhole.started -= instance.OnModeWhole;
            @ModeWhole.performed -= instance.OnModeWhole;
            @ModeWhole.canceled -= instance.OnModeWhole;
            @ModeSuperior.started -= instance.OnModeSuperior;
            @ModeSuperior.performed -= instance.OnModeSuperior;
            @ModeSuperior.canceled -= instance.OnModeSuperior;
            @ModeInferior.started -= instance.OnModeInferior;
            @ModeInferior.performed -= instance.OnModeInferior;
            @ModeInferior.canceled -= instance.OnModeInferior;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @MoveY.started -= instance.OnMoveY;
            @MoveY.performed -= instance.OnMoveY;
            @MoveY.canceled -= instance.OnMoveY;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
            @CycleMode.started -= instance.OnCycleMode;
            @CycleMode.performed -= instance.OnCycleMode;
            @CycleMode.canceled -= instance.OnCycleMode;
            @MoveUp.started -= instance.OnMoveUp;
            @MoveUp.performed -= instance.OnMoveUp;
            @MoveUp.canceled -= instance.OnMoveUp;
            @MoveDown.started -= instance.OnMoveDown;
            @MoveDown.performed -= instance.OnMoveDown;
            @MoveDown.canceled -= instance.OnMoveDown;
            @ResetTransform.started -= instance.OnResetTransform;
            @ResetTransform.performed -= instance.OnResetTransform;
            @ResetTransform.canceled -= instance.OnResetTransform;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ManipulationActions.UnregisterCallbacks(IManipulationActions)" />.
        /// </summary>
        /// <seealso cref="ManipulationActions.UnregisterCallbacks(IManipulationActions)" />
        public void RemoveCallbacks(IManipulationActions instance)
        {
            if (m_Wrapper.m_ManipulationActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ManipulationActions.AddCallbacks(IManipulationActions)" />
        /// <seealso cref="ManipulationActions.RemoveCallbacks(IManipulationActions)" />
        /// <seealso cref="ManipulationActions.UnregisterCallbacks(IManipulationActions)" />
        public void SetCallbacks(IManipulationActions instance)
        {
            foreach (var item in m_Wrapper.m_ManipulationActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ManipulationActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ManipulationActions" /> instance referencing this action map.
    /// </summary>
    public ManipulationActions @Manipulation => new ManipulationActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Manipulation" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ManipulationActions.AddCallbacks(IManipulationActions)" />
    /// <seealso cref="ManipulationActions.RemoveCallbacks(IManipulationActions)" />
    public interface IManipulationActions
    {
        /// <summary>
        /// Method invoked when associated input action "ModeWhole" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnModeWhole(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ModeSuperior" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnModeSuperior(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ModeInferior" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnModeInferior(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveY" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveY(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Rotate" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotate(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CycleMode" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCycleMode(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveDown(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ResetTransform" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnResetTransform(InputAction.CallbackContext context);
    }
}
